# Generated by Django 5.1.7 on 2025-06-04 05:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_month',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
