# Generated by Django 5.1.7 on 2025-05-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_student_unique_student_code_university'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='roomassignments',
            constraint=models.UniqueConstraint(fields=('student', 'room', 'created_date'), name='unique_student_room_date'),
        ),
    ]
