# Generated by Django 5.1.7 on 2025-05-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roomassignments_unique_student_room_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
