# Generated by Django 5.1.7 on 2025-04-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_roomassignments_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomassignments',
            name='bed_number',
            field=models.IntegerField(null=True),
        ),
    ]
