# Generated by Django 5.1.7 on 2025-04-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Empty', 'Empty'), ('Full', 'Full')], default='Empty', max_length=20),
        ),
    ]
