# Generated by Django 5.1.7 on 2025-05-16 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roomassignments_unique_student_room_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.building'),
        ),
    ]
