# Generated by Django 5.1.7 on 2025-04-17 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_first_access'),
        ('rooms', '0003_alter_roomassignments_bed_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomassignments',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_assignments', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='roomassignments',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_assignments', to='account.student'),
        ),
    ]
