# Generated by Django 5.1.7 on 2025-04-22 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_role'),
        ('rooms', '0003_alter_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomassignments',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='roomassignments',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='account.student'),
        ),
    ]
