# Generated by Django 5.1.7 on 2025-05-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_building_building_name'),
        ('rooms', '0003_alter_room_building'),
    ]

    operations = [
    ]
