# Generated by Django 5.1.7 on 2025-04-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('surveys', '0003_alter_surveyresponse_survey'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='surveyresponse',
            name='unique_survey_question_student',
        ),
        migrations.AddConstraint(
            model_name='surveyresponse',
            constraint=models.UniqueConstraint(fields=('question', 'student'), name='unique_question_student'),
        ),
    ]
