# Generated by Django 5.1.7 on 2025-05-06 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_remove_surveyresponse_unique_survey_question_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='surveys.surveyquestion'),
        ),
    ]
