# Generated by Django 5.1.7 on 2025-04-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KyTucXa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(null=True),
        ),
    ]
