# Generated by Django 5.1.7 on 2025-03-25 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KyTucXa', '0003_invoice_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomchangerequests',
            name='request_date',
        ),
    ]
