# Generated by Django 5.1.7 on 2025-04-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_first_access',
            field=models.BooleanField(default=True),
        ),
    ]
