# Generated by Django 5.1.7 on 2025-05-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_expo_token'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('student_code', 'university'), name='unique_student_code_university'),
        ),
    ]
