# Generated by Django 5.1.7 on 2025-04-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_first_access'),
        ('account', '0003_alter_user_role'),
    ]

    operations = [
    ]
