# Generated by Django 5.1.7 on 2025-06-05 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_student_phone_number_alter_student_university_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Số điện thoại phải đúng 10 chữ số', regex='^\\d{10}$')]),
        ),
    ]
