# Generated by Django 5.1.7 on 2025-04-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_merge_0002_user_is_first_access_0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Admin', 'Admin')], default='Student', max_length=20),
        ),
    ]
