name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # Thay đổi branch nếu cần

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PYTHONANYWHERE_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ssh.pythonanywhere.com >> ~/.ssh/known_hosts

    - name: Deploy to PythonAnywhere
      run: |
        ssh vovanhuy@ssh.pythonanywhere.com << EOF
          cd /home/y/QLKyTucXa/QLKyTucXa
          git pull origin main
          source rest-venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          touch /var/www/_pythonanywhere_com_wsgi.py
        EOF

