name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # Thay đổi branch nếu cần

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to PythonAnywhere via API
      run: |
        curl -X POST -H "Authorization: Token ${{ secrets.PYTHONANYWHERE_API_KEY }}" \
        https://www.pythonanywhere.com/api/v0/user/vovanhuy/webapps/vovanhuy.pythonanywhere.com/reload/
