# name: Deploy to PythonAnywhere

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Run update_code.sh on PythonAnywhere
#       run: |
#         curl -X POST -H "Authorization: Token ${{ secrets.PYTHONANYWHERE_API_KEY }}" \
#           -d "command=PA_TOKEN=${{ secrets.PYTHONANYWHERE_API_KEY }} bash ~/update_code.sh" \
#           https://www.pythonanywhere.com/api/v0/user/vovanhuy/consoles/execute/

# name: Deploy to PythonAnywhere

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Run update_code.sh on PythonAnywhere
#       run: |
#         curl -X POST -H "Authorization: Token ${{ secrets.PYTHONANYWHERE_API_KEY }}" \
#             -H "Content-Type: application/json" \
#             -d "command=PA_TOKEN=${{ secrets.PYTHONANYWHERE_API_KEY }} 
# name: Deploy Django to PythonAnywhere

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Check out repository
#       uses: actions/checkout@v4

#     - name: Run update_code.sh on PythonAnywhere
#       env:
#         PA_TOKEN: ${{ secrets.PYTHONANYWHERE_API_KEY }}
#       run: |
#         curl -X POST -H "Authorization: Token $PA_TOKEN" \
#              -H "Content-Type: application/json" \
#              -d "{\"command\": \"export PA_TOKEN=$PA_TOKEN && bash ~/update_code.sh\"}" \
#              https://www.pythonanywhere.com/api/v0/user/vovanhuy/consoles/
name: Deploy Django to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Django API to update code
      run: |
        curl -X GET "https://vovanhuy.pythonanywhere.com/update-code/"
