# Generated by Django 5.1.7 on 2025-06-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('announcement_type', models.CharField(max_length=50, null=True)),
                ('is_urgent', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-created_date'],
            },
        ),
    ]
