# Generated by Django 5.1.7 on 2025-04-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='notification',
            name='is_urgent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
