# Generated by Django 5.1.7 on 2025-06-03 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_room'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.room'),
        ),
    ]
