# Generated by Django 5.1.7 on 2025-06-05 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_room'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.room'),
        ),
    ]
